services:
  caddy:
    container_name: caddy
    image: caddy:2.8.4
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  authelia:
    container_name: authelia
    image: authelia/authelia:4.38.17
    restart: unless-stopped
    networks:
      - caddy
    expose:
      - 9091
    ports:
      - 9091
    volumes:
      - ./authelia-caddy:/config
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.0
    restart: unless-stopped
    networks:
      - caddy

  pygeoapi:
    container_name: pygeoapi
    build:
      context: .
      dockerfile: Dockerfile.pygeoapi
    restart: unless-stopped
    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
      - ./authelia-caddy:/pygeoapi/authelia-config
    ports:
      - 80
    environment:
      - SCRIPT_NAME=/api
    depends_on:
      - redis
      - caddy
      - authelia
    networks:
      - caddy

networks:
  caddy:
    name: caddy