---
###############################################################
#                   Authelia configuration                    #
###############################################################

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: a_very_important_secret
default_redirection_url: https://app.pygeoapi.local/api

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

# duo_api:
#  hostname: api-123456789.pygeoapi.local
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "app.pygeoapi.local"
      policy: one_factor
      resources:
        - "^/api/collections/obs.*"
      subject:
        - "group:cartologic"

    - domain: "app.pygeoapi.local"
      policy: one_factor
      resources:
        - "^/api/collections/lakes.*"
      subject:
        - "group:geobeyond"

    - domain: "app.pygeoapi.local"
      policy: one_factor
      resources:
        - "^.*\\/api(?:\\/)?(?:\\?.*)?$"
        - "^/api/static/.*"
        - "^.*\\/api\\/collections(?:\\?.*)?$"
        - "^.*\\/api\\/processes(?:\\?.*)?$"
        - "^.*\\/api\\/jobs(?:\\?.*)?$"
        - "^.*\\/api\\/openapi(?:\\?.*)?$"
        - "^.*\\/api\\/conformance(?:\\?.*)?$"
      subject:
        - "group:geobeyond"
        - "group:cartologic"

session:
  name: authelia_session
  domain: pygeoapi.local
  same_site: lax
  secret: unsecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 5M

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
