---
###############################################################
#                   Authelia configuration                    #
###############################################################

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
identity_validation:
  reset_password:
    jwt_secret: a_very_important_secret
default_redirection_url: https://app.pygeoapi.local/api

server:
  address: tcp://0.0.0.0:9091/

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m
  ldap:
    implementation: custom
    address: ldap://lldap:3890
    timeout: 5s
    start_tls: false
    base_dn: dc=pygeoapi,dc=local
    additional_users_dn: ou=people
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    attributes:
      display_name: displayName
      username: uid
      group_name: cn
      mail: mail
    user: uid=admin,ou=people,dc=pygeoapi,dc=local
    password: "super_strong_ldap_password" ## change this

access_control:
  default_policy: deny
  rules:
    - domain: "app.pygeoapi.local"
      policy: one_factor
      resources:
        - "^/api/collections/obs.*"
      subject:
        - "group:cartologic"

    - domain: "app.pygeoapi.local"
      policy: one_factor
      resources:
        - "^/api/collections/lakes.*"
      subject:
        - "group:geobeyond"

    - domain: "app.pygeoapi.local"
      policy: one_factor
      resources:
        - "^.*\\/api(?:\\/)?(?:\\?.*)?$"
        - "^/api/static/.*"
        - "^.*\\/api\\/collections(?:\\?.*)?$"
        - "^.*\\/api\\/processes(?:\\?.*)?$"
        - "^.*\\/api\\/jobs(?:\\?.*)?$"
        - "^.*\\/api\\/openapi(?:\\?.*)?$"
        - "^.*\\/api\\/conformance(?:\\?.*)?$"
      subject:
        - "group:geobeyond"
        - "group:cartologic"

session:
  name: authelia_session
  domain: pygeoapi.local
  same_site: lax
  secret: unsecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me: 5M

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
